remark: a
home: /media/ags/DATA/CODE/kaggle/pneumothorax/
#home: /home/eee/ug/15084015/aptos/
fold: 1
total_folds: 5
size: 256
top_lr: 1e-5
class_weights: None
cw_sampling: False
he_sampling: False
hard_ex_weight: 2
hard_df: weights/118_efficientnet-b5_f1_postraug2/diff.csv
num_samples: None
model_name: efficientnet-b4
ext_text: test
mean: (0.485, 0.456, 0.406)
std: (0.229, 0.224, 0.225)

pretrained: True
pretrained_path: weights/288_efficientnet-b4_f1_o/model.pth


df_path: data/train.csv
#df_path: data/nih_data/train.csv
sample_submission: data/sample_submission.csv

data_folder: data/train_png/
#data_folder: data/nih_data/images/
phases: ["train", "val"]
batch_size:
    train: 16
    val: 8
    test: 8

num_workers: 12
num_classes: 1
ep2unfreeze: 2 # <<<<<<<<<<
num_epochs: 50
base_lr: None
momentum: 0.95
patience: 3
tc_dups: False # <<<<<<<<<<<
dups_wsd: data/npy_files/good_duplicates.npy
bad_idx: data/npy_files/all_bad_duplicates.npy

