remark: deeplabv3 first time training.
home: /media/ags/DATA/CODE/kaggle/pneumothorax
#home: /home/eee/ug/15084015/aptos/
fold: 1
total_folds: 5
size: 512
top_lr: 1e-4
class_weights: None
cw_sampling: False
num_samples: None
model_name: deeplabv3
encoder:
mean: (0.485, 0.456, 0.406)
std: (0.229, 0.224, 0.225)
df_path: data/stage2/train.csv
sample_submission: data/stage2/sample_submission.csv
data_folder: data/npy_files/
phases: ["train", "val"]
batch_size:
    train: 4
    val: 2
    test: 2

num_workers: 12
num_classes: 1
ep2unfreeze: 0 # not implemented
num_epochs: 30
momentum: 0.95
patience: 3
criterion: Mixed

